# Generated by Django 4.2.1 on 2023-05-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='image',
            field=models.ImageField(blank=True, upload_to='airlines'),
        ),
    ]
